<?php
    function title_case_menu() {
        $items['title_case'] = array(
            'title' => 'Title Case',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('title_case_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['title_case_success_page'] = array(
            'title' => 'SUCCESS',
            'page callback' => 'title_case_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function title_case_form() {
        $form['text_input'] = array(
            '#title' => 'Title Case Form',
            '#type' => "textfield",
            '#description' => 'Enter some text',

    );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
    );
        return $form;
    }

    function title_case_form_submit($form, &$form_state) {
        $string = $form_state['values']['text_input'];
        $strings = explode(' ', $string);
        $_SESSION['output'] = $strings;


        $form_state['redirect'] = 'title_case_success_page';
    }


    function title_case_success(){
        $string_ouput = '';
        foreach ($_SESSION['output'] as $value ) {
            $string_ouput .= ' ' . ucfirst($value);
        }

        return $string_ouput;
    }
