<?php

function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => "Hello Friend!",
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['bye_admin'] = array(
        'title' => "Admin Logout",
        'page callback' => 'say_farewell_admin',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['bye_user'] = array(
        'title' => "User Logout",
        'page callback' => 'say_farewell_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hello() {
    return '<p>Hello my dear friend!</p>';
}

function say_farewell_admin() {
    return '<p>Goodbye Admin</p>';
}

function say_farewell_user() {
    return '<p>Bye User!</p>';
}

function greeting_user_login(&$edit, $account) {
    if($account->roles[3]) {
        drupal_set_message("Welcome to the Admin View!");
    } else {
        drupal_set_message("Nice to see you!");
    }

    //     echo '<pre>';
    // var_dump($account->roles[3]);
    // echo '</pre>';
    // exit;

    $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout($account) {
    if($account->roles[3]) {
        $_GET['destination'] = 'bye_admin';
    } else {
        $_GET['destination'] = 'bye_user';
    }
}
